#!/bin/bash
# manual_cleanup_commands.sh
# Manual commands to clean up OSTG FRR containers

echo "🧹 Manual cleanup commands for OSTG FRR containers"
echo ""
echo "1. Connect to the server:"
echo "   ssh root@svl-hp-ai-srv04"
echo ""
echo "2. Enter password when prompted: Embe1mpls.."
echo ""
echo "3. Run these commands on the server:"
echo ""
echo "   # List current containers"
echo "   docker ps -a | grep ostg-frr"
echo ""
echo "   # Stop the containers"
echo "   docker stop e07d4d70c799 3e33532f0320"
echo ""
echo "   # Remove the containers"
echo "   docker rm e07d4d70c799 3e33532f0320"
echo ""
echo "   # Verify containers are removed"
echo "   docker ps -a | grep ostg-frr"
echo ""
echo "   # Clean up unused Docker resources"
echo "   docker image prune -f"
echo "   docker volume prune -f"
echo "   docker network prune -f"
echo ""
echo "   # Exit SSH session"
echo "   exit"
echo ""
echo "📋 Container IDs to remove:"
echo "   - e07d4d70c799 (ostg-frr-2272426f-4815-41be-b455-eb1997b4878c)"
echo "   - 3e33532f0320 (ostg-frr-cf3a2d99-3efb-452a-9f79-67c719bb7d84)"
echo ""
echo "✅ After cleanup, these containers will be completely removed from the server."

